# Generated by Django 3.2.4 on 2021-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimei', models.CharField(max_length=50)),
                ('inr', models.CharField(max_length=50)),
                ('ctid', models.CharField(max_length=50)),
                ('cmid', models.CharField(max_length=50)),
                ('cpodr', models.CharField(max_length=50)),
                ('cadres', models.CharField(max_length=50)),
                ('cgorod', models.CharField(max_length=50)),
                ('cobl', models.CharField(max_length=50)),
                ('craion', models.CharField(max_length=50)),
                ('ddatan', models.DateField(max_length=50)),
                ('cname', models.CharField(max_length=70)),
            ],
        ),
    ]
