# Generated by Django 3.2.4 on 2021-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210617_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='lan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='lng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
