# Generated by Django 3.2.4 on 2021-06-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210617_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='lan',
            new_name='lat',
        ),
    ]
