# Generated by Django 3.2.4 on 2021-06-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_existterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
