# Generated by Django 3.2.4 on 2021-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20210620_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=50, null=True)),
                ('name_zona', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='errorterminal',
            name='czona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='existterminal',
            name='czona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='czona',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
