# Generated by Django 3.2.4 on 2021-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20210622_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorterminal',
            name='zona_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='existterminal',
            name='zona_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='zona_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
