# Generated by Django 3.2.4 on 2021-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20210622_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorterminal',
            name='lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='errorterminal',
            name='lng',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='existterminal',
            name='lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='existterminal',
            name='lng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
