# Generated by Django 3.2.4 on 2021-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20210623_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorterminal',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='errorterminal',
            name='lng',
        ),
    ]
