# Generated by Django 3.2.4 on 2021-06-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20210623_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistTerminal',
        ),
    ]
