# Generated by Django 3.2.4 on 2021-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_delete_existterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='exist',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
