# Generated by Django 3.2.4 on 2021-06-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_terminal_exist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='exist',
        ),
    ]
