# Generated by Django 3.2.4 on 2021-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_remove_terminal_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorterminal',
            name='cbank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='errorterminal',
            name='ctype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='errorterminal',
            name='cunn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='errorterminal',
            name='cvsoba',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cbank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='ctype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cunn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cvsoba',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
