# Generated by Django 3.2.4 on 2021-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20210628_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='right_adres',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cadres',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cbank',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cgorod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cimei',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cmid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cobl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cots',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cparta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cpodr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='craion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='ctid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='ctype',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cunn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='cvsoba',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='czona',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='ddatan',
            field=models.DateField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='inr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='zona_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cadres',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cbank',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cgorod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cimei',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cmid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cobl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cots',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cparta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cpodr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='craion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ctid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ctype',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cunn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cvsoba',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='czona',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ddatan',
            field=models.DateField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='inr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='lat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='lng',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='zona_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='terminalname',
            name='terminal_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name_zona',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zona',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
