# Generated by Django 3.2.4 on 2021-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_terminal_for_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal_for_check',
            name='cadres',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
