# Generated by Django 3.2.4 on 2021-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_terminal_for_check_cadres'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorterminal',
            name='ss_nom',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='terminal_for_check',
            name='cgorod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='terminal_for_check',
            name='cobl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='terminal_for_check',
            name='craion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
