# Generated by Django 3.2.4 on 2021-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_auto_20210630_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal_for_check',
            name='lat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='terminal_for_check',
            name='lng',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
