# Generated by Django 3.2.4 on 2021-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_auto_20210708_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_attr_name_and_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=150, null=True)),
                ('attr_count', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='terminal',
            name='info',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
