# Generated by Django 3.2.4 on 2021-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20210710_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=150, null=True)),
                ('lng', models.CharField(max_length=150, null=True)),
                ('info', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
