# Generated by Django 3.2.4 on 2021-07-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_terminal_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terminal_info',
        ),
        migrations.AddField(
            model_name='terminal',
            name='info_count',
            field=models.IntegerField(null=True),
        ),
    ]
