# Generated by Django 3.2.4 on 2021-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_auto_20210710_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='cstatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ddatap',
            field=models.DateField(max_length=150, null=True),
        ),
    ]
