# Generated by Django 3.2.4 on 2021-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0026_auto_20210711_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='info',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='info_count',
        ),
    ]
