# Generated by Django 3.2.4 on 2021-08-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0028_terminal_right_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminals', models.ManyToManyField(to='mainpage.Terminal')),
            ],
        ),
    ]
