# Generated by Django 3.2.4 on 2021-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0032_auto_20210811_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
