# Generated by Django 3.2.4 on 2021-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0033_marker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='zona_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
