# Generated by Django 3.2.4 on 2021-09-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0034_marker_zona_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='cadres',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
