# Generated by Django 3.2.4 on 2021-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0035_marker_cadres'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='cgorod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='cobl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='craion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
