# Generated by Django 3.2.4 on 2021-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0036_auto_20210901_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorterminal',
            name='cadres',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='errorterminal',
            name='ss_nom',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cadres',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cgorod',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cobl',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='craion',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='zona_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cadres',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cbank',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cgorod',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cimei',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cmemo',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cmid',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cname',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cobl',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cots',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cparta',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cpodr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='craion',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ctid',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ctype',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cunn',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cvsoba',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='czona',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ddatan',
            field=models.DateField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ddatap',
            field=models.DateField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='inr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='lat',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='lng',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='right_adres',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='right_components',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ss_nom',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='zona_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal_attr_name_and_count',
            name='attr_count',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='terminal_attr_name_and_count',
            name='attr_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name_zona',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zona',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
