# Generated by Django 3.2.4 on 2021-09-22 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0037_auto_20210922_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='right_components',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
