# Generated by Django 3.2.4 on 2021-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0041_auto_20210923_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_name_name_and_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=400, null=True)),
                ('attr_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal_part_name_and_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=400, null=True)),
                ('attr_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal_podr_name_and_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=400, null=True)),
                ('attr_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal_zona_name_and_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=400, null=True)),
                ('attr_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Terminal_attr_name_and_count',
        ),
    ]
