# Generated by Django 3.2.4 on 2021-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0042_auto_20211004_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpodr', models.CharField(max_length=400, null=True)),
                ('podr_name', models.CharField(max_length=400, null=True)),
                ('cadres', models.CharField(max_length=400, null=True)),
                ('cfio', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='cpodr',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
