# Generated by Django 3.2.4 on 2021-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0043_auto_20211005_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='lat',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='lng',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='zona_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
